# Dockerfile
FROM node:14

WORKDIR /app

# Copia dei file di configurazione e installazione delle dipendenze
COPY package*.json ./
RUN npm install

# Copia del codice dell'applicazione
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
